---
- hosts: all
  become: true
  tasks:

  - name: install python3 and pip3
    package:
      name:
        - python3
        - python3-pip
      state: latest

  - name: use pip3 as default pip in Ubuntu
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: ansible_distribution == "Ubuntu"

  - name: use pip3 as default pip in Centos
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: ansible_distribution == "CentOS"

  - name: use python3 as default python in Ubuntu
    command : "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == "Ubuntu"

  - name: use python3 as default python in Centos
    command : "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == "CentOS"

  - name: install java open-jdk in Centos
    dnf:
      name:
       - java-11-openjdk-devel
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install java open-jdk in Ubuntu
    apt:
      name: openjdk-11-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Create Motd 
    copy: 
      content: "{{ motd_text | default('Ansible Manage node by Ferrer') }}"
      dest: /etc/motd

  - name: Create user
    user:
      name: "{{ 'josephferrer' }}"
      state: present

